CREATE TABLE `notification_preferences` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`ewaApproved` boolean NOT NULL DEFAULT true,
	`ewaRejected` boolean NOT NULL DEFAULT true,
	`ewaDisbursed` boolean NOT NULL DEFAULT true,
	`treepointsReceived` boolean NOT NULL DEFAULT true,
	`treepointsRedeemed` boolean NOT NULL DEFAULT true,
	`goalProgress` boolean NOT NULL DEFAULT true,
	`goalCompleted` boolean NOT NULL DEFAULT true,
	`fwiImproved` boolean NOT NULL DEFAULT true,
	`fwiAlert` boolean NOT NULL DEFAULT true,
	`levelUp` boolean NOT NULL DEFAULT true,
	`streakMilestone` boolean NOT NULL DEFAULT true,
	`offerAvailable` boolean NOT NULL DEFAULT true,
	`systemAnnouncement` boolean NOT NULL DEFAULT true,
	`securityAlert` boolean NOT NULL DEFAULT true,
	`inAppEnabled` boolean NOT NULL DEFAULT true,
	`emailEnabled` boolean NOT NULL DEFAULT false,
	`pushEnabled` boolean NOT NULL DEFAULT false,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `notification_preferences_id` PRIMARY KEY(`id`),
	CONSTRAINT `notification_preferences_userId_unique` UNIQUE(`userId`)
);
--> statement-breakpoint
CREATE TABLE `notifications` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`type` enum('ewa_approved','ewa_rejected','ewa_disbursed','treepoints_received','treepoints_redeemed','goal_progress','goal_completed','fwi_improved','fwi_alert','level_up','streak_milestone','offer_available','system_announcement','security_alert') NOT NULL,
	`title` varchar(200) NOT NULL,
	`message` text NOT NULL,
	`icon` varchar(50),
	`actionUrl` varchar(500),
	`actionLabel` varchar(100),
	`metadata` text,
	`isRead` boolean NOT NULL DEFAULT false,
	`readAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `notifications_id` PRIMARY KEY(`id`)
);
