CREATE TABLE `alert_history` (
	`id` int AUTO_INCREMENT NOT NULL,
	`ruleId` int NOT NULL,
	`alertType` enum('fwi_department_low','fwi_individual_low','fwi_trend_negative','ewa_pending_count','ewa_pending_amount','ewa_user_excessive','high_risk_percentage','new_high_risk_user','weekly_risk_summary') NOT NULL,
	`departmentId` int,
	`userId` int,
	`previousValue` int,
	`currentValue` int NOT NULL,
	`threshold` int NOT NULL,
	`message` text NOT NULL,
	`severity` enum('info','warning','critical') NOT NULL DEFAULT 'warning',
	`notifiedViaEmail` boolean NOT NULL DEFAULT false,
	`notifiedViaPush` boolean NOT NULL DEFAULT false,
	`notifiedViaInApp` boolean NOT NULL DEFAULT false,
	`notifiedUsers` text,
	`acknowledgedBy` int,
	`acknowledgedAt` timestamp,
	`resolvedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `alert_history_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `alert_rules` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(255) NOT NULL,
	`description` text,
	`alertType` enum('fwi_department_low','fwi_individual_low','fwi_trend_negative','ewa_pending_count','ewa_pending_amount','ewa_user_excessive','high_risk_percentage','new_high_risk_user','weekly_risk_summary') NOT NULL,
	`threshold` int NOT NULL,
	`comparisonOperator` enum('lt','lte','gt','gte','eq') NOT NULL DEFAULT 'lt',
	`departmentId` int,
	`isEnabled` boolean NOT NULL DEFAULT true,
	`notifyEmail` boolean NOT NULL DEFAULT true,
	`notifyPush` boolean NOT NULL DEFAULT true,
	`notifyInApp` boolean NOT NULL DEFAULT true,
	`notifyAdmins` boolean NOT NULL DEFAULT true,
	`notifyB2BAdmin` boolean NOT NULL DEFAULT true,
	`cooldownMinutes` int NOT NULL DEFAULT 60,
	`createdBy` int NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `alert_rules_id` PRIMARY KEY(`id`)
);
