CREATE TABLE `monthly_metrics_snapshots` (
	`id` int AUTO_INCREMENT NOT NULL,
	`organizationId` int,
	`departmentId` int,
	`year` int NOT NULL,
	`month` int NOT NULL,
	`avgFwiScore` int NOT NULL,
	`totalEmployees` int NOT NULL,
	`employeesAtRisk` int NOT NULL DEFAULT 0,
	`riskPercentage` int NOT NULL DEFAULT 0,
	`totalEwaRequests` int NOT NULL DEFAULT 0,
	`totalEwaAmount` int NOT NULL DEFAULT 0,
	`avgEngagementScore` int DEFAULT 0,
	`totalTreePointsEarned` int NOT NULL DEFAULT 0,
	`totalTreePointsRedeemed` int NOT NULL DEFAULT 0,
	`goalsCreated` int NOT NULL DEFAULT 0,
	`goalsCompleted` int NOT NULL DEFAULT 0,
	`alertsTriggered` int NOT NULL DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `monthly_metrics_snapshots_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `organization_alert_thresholds` (
	`id` int AUTO_INCREMENT NOT NULL,
	`organizationId` int NOT NULL,
	`fwiCriticalThreshold` int NOT NULL DEFAULT 30,
	`fwiWarningThreshold` int NOT NULL DEFAULT 50,
	`fwiHealthyThreshold` int NOT NULL DEFAULT 70,
	`riskCriticalPercentage` int NOT NULL DEFAULT 25,
	`riskWarningPercentage` int NOT NULL DEFAULT 15,
	`ewaMaxPendingCount` int NOT NULL DEFAULT 10,
	`ewaMaxPendingAmount` int NOT NULL DEFAULT 50000,
	`ewaMaxPerEmployee` int NOT NULL DEFAULT 3,
	`notifyOnCritical` boolean NOT NULL DEFAULT true,
	`notifyOnWarning` boolean NOT NULL DEFAULT true,
	`notifyOnInfo` boolean NOT NULL DEFAULT false,
	`notifyEmails` text,
	`notifySlackWebhook` varchar(500),
	`createdBy` int NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `organization_alert_thresholds_id` PRIMARY KEY(`id`)
);
